# Generated by Django 3.2.16 on 2025-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_salarydynamycsall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='citysalarydynamicsall',
            name='name',
            field=models.CharField(default='def', max_length=30),
        ),
        migrations.AddField(
            model_name='citysalaryshareall',
            name='name',
            field=models.CharField(default='def', max_length=30),
        ),
        migrations.AddField(
            model_name='vacancydynamycsall',
            name='name',
            field=models.CharField(default='def', max_length=30),
        ),
    ]
