# Generated by Django 3.2.16 on 2025-01-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20250114_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citysalarydynamicsall',
            name='name',
        ),
        migrations.RemoveField(
            model_name='citysalaryshareall',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salarydynamycsall',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacancydynamycsall',
            name='name',
        ),
    ]
