# Generated by Django 3.2.16 on 2025-01-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_topskills2015_topskills2016_topskills2017_topskills2018_topskills2019_topskills2020_topskills2021_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDynamycsProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDynamycsProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
