# Generated by Django 3.2.16 on 2025-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_salarydynamycsprof_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySalaryDynamycs_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_all', models.IntegerField(verbose_name='Города (ВСЕ)')),
                ('salary_all', models.IntegerField(verbose_name='Средняя зарплата (ВСЕ)')),
                ('city_prof', models.IntegerField(verbose_name='Города (iOS)')),
                ('salary_prof', models.IntegerField(verbose_name='Средняя зарплата (iOS)')),
            ],
        ),
    ]
