# Generated by Django 3.2.16 on 2025-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_citysalarydynamycs_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysalarydynamycs_table',
            name='city_all',
            field=models.CharField(max_length=50, verbose_name='Города (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='citysalarydynamycs_table',
            name='city_prof',
            field=models.CharField(max_length=50, verbose_name='Города (iOS)'),
        ),
    ]
