# Generated by Django 3.2.16 on 2025-01-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20250114_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySalaryShare_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_all', models.CharField(max_length=50, verbose_name='Города (ВСЕ)')),
                ('share_all', models.IntegerField(verbose_name='Доля вакансий (ВСЕ)')),
                ('city_prof', models.CharField(max_length=50, verbose_name='Города (iOS)')),
                ('share_prof', models.IntegerField(verbose_name='Доля вакансий (iOS)')),
            ],
        ),
    ]
