# Generated by Django 3.2.16 on 2025-01-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_citysalaryshare_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysalaryshare_table',
            name='share_all',
            field=models.FloatField(verbose_name='Доля вакансий (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='citysalaryshare_table',
            name='share_prof',
            field=models.FloatField(verbose_name='Доля вакансий (iOS)'),
        ),
    ]
