# Generated by Django 3.2.16 on 2025-01-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_skills_table_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills_table_2015',
            old_name='num',
            new_name='number',
        ),
    ]
