# Generated by Django 3.2.16 on 2025-01-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_rename_num_skills_table_2015_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Table_2016',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Топ')),
                ('skills_all', models.CharField(max_length=50, verbose_name='Навыки (ВСЕ)')),
                ('freq_all', models.IntegerField(verbose_name='Частотность (ВСЕ)')),
                ('skills_prof', models.CharField(max_length=50, verbose_name='Навыки (iOS)')),
                ('freq_prof', models.IntegerField(verbose_name='Частотность (iOS)')),
            ],
        ),
    ]
