# Generated by Django 3.2.16 on 2025-01-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_skills_table_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Table_2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Топ')),
                ('skills_all', models.CharField(max_length=50, verbose_name='Навыки (ВСЕ)')),
                ('freq_all', models.IntegerField(verbose_name='Частотность (ВСЕ)')),
                ('skills_prof', models.CharField(max_length=50, verbose_name='Навыки (iOS)')),
                ('freq_prof', models.IntegerField(verbose_name='Частотность (iOS)')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Table_2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Топ')),
                ('skills_all', models.CharField(max_length=50, verbose_name='Навыки (ВСЕ)')),
                ('freq_all', models.IntegerField(verbose_name='Частотность (ВСЕ)')),
                ('skills_prof', models.CharField(max_length=50, verbose_name='Навыки (iOS)')),
                ('freq_prof', models.IntegerField(verbose_name='Частотность (iOS)')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Table_2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Топ')),
                ('skills_all', models.CharField(max_length=50, verbose_name='Навыки (ВСЕ)')),
                ('freq_all', models.IntegerField(verbose_name='Частотность (ВСЕ)')),
                ('skills_prof', models.CharField(max_length=50, verbose_name='Навыки (iOS)')),
                ('freq_prof', models.IntegerField(verbose_name='Частотность (iOS)')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Table_2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Топ')),
                ('skills_all', models.CharField(max_length=50, verbose_name='Навыки (ВСЕ)')),
                ('freq_all', models.IntegerField(verbose_name='Частотность (ВСЕ)')),
                ('skills_prof', models.CharField(max_length=50, verbose_name='Навыки (iOS)')),
                ('freq_prof', models.IntegerField(verbose_name='Частотность (iOS)')),
            ],
        ),
    ]
